// Vietnamese display copy for BE permission codes, keyed by `code` per the
// Owner Control Center BA spec (section 6). Codes are the technical contract;
// never derive labels by splitting the code string.

export const PERMISSION_LABEL: Record<string, string> = {
  "patient.read.assigned": "Xem bệnh nhân được phân công",
  "patient.read.organization": "Xem bệnh nhân trong tổ chức",
  "patient.write.contact": "Sửa thông tin liên hệ bệnh nhân",
  "patient.write.clinical": "Sửa thông tin lâm sàng/quản trị bệnh nhân",
  "consent.manage.self": "Quản lý đồng thuận của bản thân",
  "appointment.book": "Đặt lịch hẹn",
  "appointment.manage": "Quản lý lịch hẹn",
  "checkin.qr_redeem": "Xác nhận check-in QR",
  "queue.view": "Xem hàng đợi",
  "queue.call": "Gọi và chuyển lượt hàng đợi",
  "encounter.create": "Tạo lượt khám",
  "encounter.transition": "Chuyển trạng thái lượt khám",
  "encounter.close": "Đóng lượt khám",
  "diagnosis.create": "Ghi hoặc sửa chẩn đoán",
  "clinical_order.create": "Tạo chỉ định lâm sàng",
  "clinical_order.result": "Ghi kết quả chỉ định",
  "clinical_plan.approve": "Duyệt kế hoạch điều trị",
  "record.sign": "Ký hoặc mở lại hồ sơ y tế",
  "workflow_task.execute": "Thực hiện tác vụ quy trình",
  "workflow_template.author": "Soạn mẫu quy trình",
  "workflow_template.publish": "Xuất bản/lưu trữ mẫu quy trình",
  "user.invite": "Mời tài khoản nhân viên",
  "user.lock": "Khóa/mở khóa tài khoản",
  "user.role.assign": "Gán/thu hồi vai trò",
  "clinic.manage": "Quản lý tổ chức/phòng khám/phòng ban",
  "feature_flag.toggle": "Bật/tắt tính năng",
  "audit.view": "Xem nhật ký kiểm toán",
  "break_glass.request": "Yêu cầu truy cập khẩn cấp",
  "dangerous_action.propose": "Đề xuất tác vụ nguy hiểm",
  "dangerous_action.approve": "Phê duyệt tác vụ nguy hiểm",
  "owner.add": "Thêm Platform Owner",
  "security.revoke_all_sessions": "Thu hồi toàn bộ phiên đăng nhập",
  "directory.export_bulk": "Xuất toàn bộ danh bạ",
  "membership.revoke_bulk": "Thu hồi hàng loạt membership",
  "audit.disable": "Tạm dừng audit không trọng yếu",
};

export const PERMISSION_GROUP: Record<string, string> = {
  "patient.read.assigned": "Bệnh nhân",
  "patient.read.organization": "Bệnh nhân",
  "patient.write.contact": "Bệnh nhân",
  "patient.write.clinical": "Bệnh nhân",
  "consent.manage.self": "Đồng thuận",
  "appointment.book": "Lịch hẹn",
  "appointment.manage": "Lịch hẹn",
  "checkin.qr_redeem": "Check-in",
  "queue.view": "Hàng đợi",
  "queue.call": "Hàng đợi",
  "encounter.create": "Khám bệnh",
  "encounter.transition": "Khám bệnh",
  "encounter.close": "Khám bệnh",
  "diagnosis.create": "Lâm sàng",
  "clinical_order.create": "Lâm sàng",
  "clinical_order.result": "Lâm sàng",
  "clinical_plan.approve": "Lâm sàng",
  "record.sign": "Hồ sơ y tế",
  "workflow_task.execute": "Quy trình",
  "workflow_template.author": "Quy trình",
  "workflow_template.publish": "Quy trình",
  "user.invite": "Người dùng",
  "user.lock": "Người dùng",
  "user.role.assign": "Người dùng",
  "clinic.manage": "Hệ thống",
  "feature_flag.toggle": "Hệ thống",
  "audit.view": "Kiểm toán",
  "break_glass.request": "Khẩn cấp",
  "dangerous_action.propose": "Quản trị cấp cao",
  "dangerous_action.approve": "Quản trị cấp cao",
  "owner.add": "Nguy hiểm",
  "security.revoke_all_sessions": "Nguy hiểm",
  "directory.export_bulk": "Nguy hiểm",
  "membership.revoke_bulk": "Nguy hiểm",
  "audit.disable": "Nguy hiểm",
};

export function permissionLabel(
  code: string,
  description?: string | null,
): string {
  return PERMISSION_LABEL[code] ?? description ?? code;
}
