// Vietnamese display copy for BE permission codes, keyed by `code` per the
// Owner Control Center BA spec (section 6). Codes are the technical contract;
// never derive labels by splitting the code string.

export const PERMISSION_LABEL: Record<string, string> = {
  "module.dashboard.view": "Mở Tổng quan",
  "module.appointments.access": "Mở Lịch hẹn",
  "module.profile.access": "Mở Hồ sơ bệnh nhân",
  "module.ai_analysis.access": "Mở Phân tích da bằng AI",
  "module.journey.access": "Mở Tiến trình khám bệnh",
  "module.doctor_review.access": "Mở Xem xét & Chẩn đoán",
  "module.work_queue.access": "Mở Hàng đợi công việc",
  "module.workflow_design.access": "Mở Thiết kế quy trình BPM",
  "module.records.access": "Mở Bệnh án trọn đời",
  "module.progress.access": "Mở Theo dõi tiến triển",
  "module.care.access": "Mở Chăm sóc sau khám",
  "module.prescriptions.access": "Mở Đơn thuốc",
  "module.reports.access": "Mở Báo cáo",
  "module.checkin.access": "Mở Check-in QR",
  "module.reception.access": "Mở Trung tâm lễ tân",
  "module.queue.access": "Mở Điều phối hàng đợi",
  "module.audit.access": "Mở Nhật ký kiểm toán",
  "module.integrations.access": "Mở Tình trạng tích hợp",
  "module.staff.access": "Mở Quản lý nhân sự",
  "module.practitioner_schedule.access": "Mở Lịch làm việc bác sĩ",
  "module.owner.access": "Mở Owner Control Center",
  "module.settings.access": "Mở Cài đặt",
  "module.support.access": "Mở Hỗ trợ",
  "patient.read.assigned": "Xem bệnh nhân được phân công",
  "patient.read.organization": "Xem bệnh nhân trong tổ chức",
  "patient.write.contact": "Sửa thông tin liên hệ bệnh nhân",
  "patient.write.clinical": "Sửa thông tin lâm sàng/quản trị bệnh nhân",
  "consent.manage.self": "Quản lý đồng thuận của bản thân",
  "appointment.book": "Đặt lịch hẹn",
  "appointment.manage": "Quản lý lịch hẹn",
  "checkin.qr_redeem": "Xác nhận check-in QR",
  "queue.view": "Xem hàng đợi",
  "queue.call": "Gọi và chuyển lượt hàng đợi",
  "encounter.create": "Tạo lượt khám",
  "encounter.transition": "Chuyển trạng thái lượt khám",
  "encounter.close": "Đóng lượt khám",
  "diagnosis.create": "Ghi hoặc sửa chẩn đoán",
  "clinical_order.create": "Tạo chỉ định lâm sàng",
  "clinical_order.result": "Ghi kết quả chỉ định",
  "clinical_plan.approve": "Duyệt kế hoạch điều trị",
  "record.sign": "Ký hoặc mở lại hồ sơ y tế",
  "workflow_task.execute": "Thực hiện tác vụ quy trình",
  "workflow_template.author": "Soạn mẫu quy trình",
  "workflow_template.publish": "Xuất bản/lưu trữ mẫu quy trình",
  "user.invite": "Mời tài khoản nhân viên",
  "user.lock": "Khóa/mở khóa tài khoản",
  "user.role.assign": "Gán/thu hồi vai trò",
  "clinic.manage": "Quản lý tổ chức/phòng khám/phòng ban",
  "feature_flag.toggle": "Bật/tắt tính năng",
  "audit.view": "Xem nhật ký kiểm toán",
  "break_glass.request": "Yêu cầu truy cập khẩn cấp",
  "dangerous_action.propose": "Đề xuất tác vụ nguy hiểm",
  "dangerous_action.approve": "Phê duyệt tác vụ nguy hiểm",
  "owner.add": "Thêm Platform Owner",
  "security.revoke_all_sessions": "Thu hồi toàn bộ phiên đăng nhập",
  "directory.export_bulk": "Xuất toàn bộ danh bạ",
  "membership.revoke_bulk": "Thu hồi hàng loạt membership",
  "audit.disable": "Tạm dừng audit không trọng yếu",
};

export const PERMISSION_GROUP: Record<string, string> = {
  "module.dashboard.view": "Truy cập tính năng",
  "module.appointments.access": "Truy cập tính năng",
  "module.profile.access": "Truy cập tính năng",
  "module.ai_analysis.access": "Truy cập tính năng",
  "module.journey.access": "Truy cập tính năng",
  "module.doctor_review.access": "Truy cập tính năng",
  "module.work_queue.access": "Truy cập tính năng",
  "module.workflow_design.access": "Truy cập tính năng",
  "module.records.access": "Truy cập tính năng",
  "module.progress.access": "Truy cập tính năng",
  "module.care.access": "Truy cập tính năng",
  "module.prescriptions.access": "Truy cập tính năng",
  "module.reports.access": "Truy cập tính năng",
  "module.checkin.access": "Truy cập tính năng",
  "module.reception.access": "Truy cập tính năng",
  "module.queue.access": "Truy cập tính năng",
  "module.audit.access": "Truy cập tính năng",
  "module.integrations.access": "Truy cập tính năng",
  "module.staff.access": "Truy cập tính năng",
  "module.practitioner_schedule.access": "Truy cập tính năng",
  "module.owner.access": "Truy cập tính năng",
  "module.settings.access": "Truy cập tính năng",
  "module.support.access": "Truy cập tính năng",
  "patient.read.assigned": "Bệnh nhân",
  "patient.read.organization": "Bệnh nhân",
  "patient.write.contact": "Bệnh nhân",
  "patient.write.clinical": "Bệnh nhân",
  "consent.manage.self": "Đồng thuận",
  "appointment.book": "Lịch hẹn",
  "appointment.manage": "Lịch hẹn",
  "checkin.qr_redeem": "Check-in",
  "queue.view": "Hàng đợi",
  "queue.call": "Hàng đợi",
  "encounter.create": "Khám bệnh",
  "encounter.transition": "Khám bệnh",
  "encounter.close": "Khám bệnh",
  "diagnosis.create": "Lâm sàng",
  "clinical_order.create": "Lâm sàng",
  "clinical_order.result": "Lâm sàng",
  "clinical_plan.approve": "Lâm sàng",
  "record.sign": "Hồ sơ y tế",
  "workflow_task.execute": "Quy trình",
  "workflow_template.author": "Quy trình",
  "workflow_template.publish": "Quy trình",
  "user.invite": "Người dùng",
  "user.lock": "Người dùng",
  "user.role.assign": "Người dùng",
  "clinic.manage": "Hệ thống",
  "feature_flag.toggle": "Hệ thống",
  "audit.view": "Kiểm toán",
  "break_glass.request": "Khẩn cấp",
  "dangerous_action.propose": "Quản trị cấp cao",
  "dangerous_action.approve": "Quản trị cấp cao",
  "owner.add": "Nguy hiểm",
  "security.revoke_all_sessions": "Nguy hiểm",
  "directory.export_bulk": "Nguy hiểm",
  "membership.revoke_bulk": "Nguy hiểm",
  "audit.disable": "Nguy hiểm",
};

export function permissionLabel(
  code: string,
  description?: string | null,
): string {
  return PERMISSION_LABEL[code] ?? description ?? code;
}

// Color is reserved for permissions that carry real risk, not a rainbow per
// category — matches how Tag color is used elsewhere in the app (severity,
// success/warning/error), never as decoration.
export function permissionColor(code: string): string | undefined {
  return PERMISSION_GROUP[code] === "Nguy hiểm" ? "error" : undefined;
}

/**
 * Minimum self-service bundle required by the patient web journey. The server
 * remains authoritative and still scopes patient data to the authenticated
 * person's own record.
 */
export const PATIENT_SELF_SERVICE_PERMISSIONS = [
  "patient.read.assigned",
  "patient.write.contact",
  "consent.manage.self",
  "appointment.book",
  "queue.view",
  "workflow_task.execute",
] as const;
